//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitas_Stock.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public int id_lote { get; set; }
        public Nullable<int> cod_articulo { get; set; }
        public string fecha_ingreso { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string fecha_venc { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
